<?php
/**
 * Created by PhpStorm.
 * User: gt
 * Date: 19-2-13
 * Time: 上午12:08
 */

namespace app\admin\controller;


use app\common\lib\CrudBaseTrait;
use app\common\lib\SoftDeleteControllerTrait;
use app\common\model\ImportantModel;
use think\Controller;

class ImportantController extends Controller
{
    use CrudBaseTrait;
    use SoftDeleteControllerTrait;


    protected function initialize()
    {
        $this->model = new ImportantModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function unlock(){
        return success($this->model->unlock(input('id'),input('secret_key')));
    }
}