<?php
/**
 * Created by PhpStorm.
 * User: gtguizhou
 * Date: 19-3-26
 * Time: 下午8:44
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\MusicModel;

class MusicController extends ApiBase
{
    protected function initialize()
    {
        $this->model = new MusicModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $limitAction = ['except' => 'indexAll'];
}