<?php
/**
 * Created by PhpStorm.
 * User: gt
 * Date: 19-2-6
 * Time: 下午12:25
 */

namespace app\api\controller;


use app\common\controller\ApiBase;
use app\common\model\SysConfigModel;

class SysconfigController extends ApiBase
{
    protected $limitAction = [
        'except' => 'indexAll'
    ];

    protected function initialize()
    {
        $this->model = new SysConfigModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAll()
    {
        // 将索引变为field
        $res = $this->model->select();
        $config = [];
        foreach ($res as &$val){
            $config[$val['field']] = $val;
        }
        return success($config);
    }
}